research_task:
  description: >
    Realiza una investigación exhaustiva sobre {topic} y los subtemas de {topic}
    Asegúrate de encontrar cualquier información interesante y relevante dado
    que el año actual es {current_year}.
  expected_output: >
    Una lista con todos los puntos que encontraste necesarios y destacados de la
    información más relevante sobre {topic} y los subtemas de {topic}.
  agent: researcher

screenwriting_task:
  description: >
    Revisa el contexto obtenido y además busca por la estructura de un guión dentro
    del guión base que vas a usar como referencia, toma en cuenta sobre todo
    el tono y la estructura de este guión para crear uno similar pero con el contenido
    del contexto. Escribe un guión como sólo tú sabes hacerlo con esa información, recuerda basarte el guión previo.
    Utiliza la herramienta de `@notion_tool()` para crear una página y guardar el título y el contenido del guión.
  expected_output: >
    Un guión atractivo, interesante, divertido y educativo para un video de YouTube.
    Regresa el título del video y el contenido formateado como markdown sin '```'
  agent: screenwriter
